const PrivacyPolicy = () => {
  return (
    <div className="bg-gray-50 min-h-screen py-10 px-6 md:px-20">
      <div className="max-w-4xl mx-auto text-start bg-white text-black shadow-lg rounded-2xl p-8 md:p-12">
        {/* Title */}
        <div className="w-full text-center ">
          <h3 className="text-3xl font-medium mb-2">
            FutureMindsPrivacy Policy
          </h3>
          <p className="text-sm text-gray-400 mb-6">
            Last updated: September 14, 2025
          </p>
        </div>

        <div className="space-y-2 leading-relaxed text-gray-700">
          <p>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </div>

        <h4 className="text-2xl font-semibold text-gray-800 mt-4 mb-4">
          Interpretation and Definitions
        </h4>

        <h3 className="text-xl font-semibold text-gray-700 mb-2">
          Interpretation
        </h3>
        <p className="mb-4 leading-relaxed text-gray-700">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className="text-xl font-semibold text-gray-800 mb-2">
          Definitions
        </h3>
        <p className="mb-4">For the purposes of this Privacy Policy:</p>

        {/* Lists */}
        <ul className="list-disc list-inside space-y-3 mb-6 text-gray-700">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest or other securities entitled to vote for election of
            directors or other managing authority.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to Future Minds Institute.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website.
          </li>
          <li>
            <strong>Country</strong> refers to: Uttar Pradesh, India
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself.
          </li>
          <li>
            <strong>Website</strong> refers to Future Minds Institute,
            accessible from{" "}
            <a
              href="https://www.futuremindsinstitute.com/"
              rel="noopener noreferrer"
              target="_blank"
              className="text-blue-600 underline hover:text-blue-800"
            >
              https://www.futuremindsinstitute.com/
            </a>
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        {/* Example of next section */}
        <h3 className="text-2xl font-semibold text-gray-900 mt-10 mb-4">
          Collecting and Using Your Personal Data
        </h3>

        <h3 className="text-xl font-semibold text-gray-800 mb-2">
          Types of Data Collected
        </h3>
        <h4 className="text-lg font-semibold text-gray-700 mb-2">
          Personal Data
        </h4>
        <p className="mb-4 leading-relaxed">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include:
        </p>

        <ul className="list-disc list-inside space-y-2 mb-6 text-gray-700">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
